---
- name: symplegma-os_bootstrap
  scm: git
  src: https://github.com/particuleio/symplegma-os_bootstrap.git
  version: v1.11.0
- name: symplegma-kubernetes_hosts
  scm: git
  src: https://github.com/particuleio/symplegma-kubernetes_hosts
  version: v1.19.2-rel.0
- name: symplegma-kubeadm
  scm: git
  src: https://github.com/particuleio/symplegma-kubeadm
  version: v1.19.2-rel.1
- name: symplegma-containerd
  scm: git
  src: https://github.com/particuleio/symplegma-containerd
  version: v1.4.1-rel.1
- name: symplegma-cni
  scm: git
  src: https://github.com/particuleio/symplegma-cni
  version: v0.8.7-rel.0
- name: symplegma-calico
  scm: git
  src: https://github.com/particuleio/symplegma-calico
  version: v3.16.1-rel.1
- name: symplegma-flannel
  scm: git
  src: https://github.com/particuleio/symplegma-flannel
  version: v0.12.0-rel.1
- name: symplegma-win_cni
  scm: git
  src: https://github.com/particuleio/symplegma-win_cni
  version: v0.8.6
- name: symplegma-win_kubernetes_hosts
  scm: git
  src: https://github.com/particuleio/symplegma-win_kubernetes_hosts
  version: v1.18.6-rel.1
- name: symplegma-win_docker
  scm: git
  src: https://github.com/particuleio/symplegma-win_docker
  version: v1.0.0
