---
- name: symplegma-os_bootstrap
  scm: git
  src: https://github.com/particuleio/symplegma-os_bootstrap.git
  version: v2.0.0
- name: symplegma-kubernetes_hosts
  scm: git
  src: https://github.com/particuleio/symplegma-kubernetes_hosts
  version: v1.37.0-rel.0
- name: symplegma-kubeadm
  scm: git
  src: https://github.com/particuleio/symplegma-kubeadm
  version: v1.37.0-rel.0
- name: symplegma-containerd
  scm: git
  src: https://github.com/particuleio/symplegma-containerd
  version: v2.3.5-rel.1
- name: symplegma-crio
  scm: git
  src: https://github.com/particuleio/symplegma-crio
  version: v1.36.5-rel.1
- name: symplegma-cni
  scm: git
  src: https://github.com/particuleio/symplegma-cni
  version: v1.9.1-rel.0
- name: symplegma-flannel
  scm: git
  src: https://github.com/particuleio/symplegma-flannel
  version: v0.28.9-rel.0
