---
- hosts: master:node
  gather_facts: false
  roles:
    - symplegma-os_bootstrap
  tags:
    - bootstrap

- hosts: master:node
  serial: 1
  roles:
    - role: symplegma-containerd
      tags:
        - containerd
    - role: symplegma-cni
      tags:
        - cni
    - role: symplegma-kubernetes_hosts
      tags:
        - kubernetes_hosts

- hosts: master
  serial: 1
  roles:
    - role: symplegma-kubeadm/master
      tags:
        - kubeadm-master

- hosts: node
  serial: 1
  roles:
    - role: symplegma-kubeadm/node
      tags:
        - kubeadm-node

- hosts: master
  roles:
    - role: symplegma-calico
      tags: calico
      when: cni_plugin == "calico"
