---
- name: Reset Linux Kubernetes nodes
  hosts: master:node
  vars_files:
    - defaults/main.yml
  tasks:
    - name: Reset | Run Kubeadm reset on node
      ansible.builtin.shell: |
        {{ bin_dir }}/kubeadm reset -f --cri-socket "{{ cri_socket }}"
    - name: Reset | Cleanup /root
      ansible.builtin.file:
        path: "/root/{{ item }}"
        state: absent
      with_items:
        - kubeadm-config.yaml
        - rbac-kdd.yaml
        - calico.yaml
    - name: Reset | CNI config
      ansible.builtin.file:
        path: "/etc/cni/net.d"
        state: absent
    - name: Reset | CNI config
      ansible.builtin.file:
        path: "/etc/cni/net.d"
        state: directory
    - name: Reset | Cleanup leftover pods
      ansible.builtin.shell: |
        {{ bin_dir }}/crictl --runtime-endpoint {{ cri_socket }} pods -q | xargs -r {{ bin_dir }}/crictl --runtime-endpoint {{ cri_socket }} stopp
        {{ bin_dir }}/crictl --runtime-endpoint {{ cri_socket }} pods -q | xargs -r {{ bin_dir }}/crictl --runtime-endpoint {{ cri_socket }} rmp
    - name: Reset | Restart services
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: true
        name: "{{ item }}"
        no_block: true
      loop:
        - kubelet
        - "{{ container_runtime | default('containerd') }}"
    - name: Reset | Reenable SWAP in fstab (1/2)
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: '^# (.+?\sswap\s+sw\s+.*)$'
        replace: '\1'
    - name: Reset | Enable SWAP (2/2)
      ansible.builtin.shell: |
        swapon -a
