---
- hosts: master:node
  gather_facts: false
  roles:
    - symplegma-os_bootstrap
  tags:
    - bootstrap

- hosts: master:node
  vars_files:
    - defaults/main.yml
  roles:
    - role: symplegma-containerd
      tags:
        - containerd
      when: container_runtime == "containerd"
    - role: symplegma-crio
      tags:
        - crio
      when: container_runtime == "crio"
    - role: symplegma-cni
      tags:
        - cni
    - role: symplegma-kubernetes_hosts
      tags:
        - kubernetes_hosts

- hosts: master
  vars_files:
    - defaults/main.yml
  roles:
    - role: symplegma-kubeadm/master
      tags:
        - kubeadm-master

- hosts: node
  vars_files:
    - defaults/main.yml
  roles:
    - role: symplegma-kubeadm/node
      tags:
        - kubeadm-node

- hosts: master
  vars_files:
    - defaults/main.yml
  roles:
    - role: symplegma-calico
      tags: calico
      when: cni_plugin == "calico"
    - role: symplegma-flannel
      tags: flannel
      when: cni_plugin == "flannel"

- hosts: win_node
  vars_files:
    - defaults/main.yml
  roles:
    - role: symplegma-win_docker
      tags:
        - win_docker
    - role: symplegma-win_cni
      tags:
        - win_cni
    - role: symplegma-win_kubernetes_hosts
      tags:
        - win_kubernetes_hosts
    - role: symplegma-kubeadm/win_node
      tags:
        - kubeadm-win_node
