---
name: 'symplegma:mkdocs'

'on':
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'README.md'
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'README.md'

jobs:
  terraform:
    name: 'symplegma:mkdocs'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up python3
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: install ansible
        run: pip3 install ansible

      - name: install symplegma roles
        run: ansible-galaxy install -r requirements.yml

      - name: deploy
        if: github.ref == 'refs/heads/main'
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REQUIREMENTS: docs/requirements.txt
