name: 'check-renovate-config'

on:
  push:
    branches:
    - main
    - release
    paths:
    - '.github/renovate.json'
  pull_request:
    branches:
      - main
      - release
    paths:
    - '.github/renovate.json'
  workflow_dispatch:

jobs:
  renovate-config-check:
    name: 'renovate:config'
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '15'
        check-latest: true

    - name: Install Renovate
      run: npm install -g renovate

    - name: Check Renovate configuraton
      run: renovate-config-validator
